# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
permalink: amcw7777.github.io/:year-:month-:day-:title/
# relative_permalinks: auto

# Setup
title:               Liang(Leon) He
tagline:             'Personal Website'
description:         "Leon's personal website about academia and life"
url:                 http://lanyon.getpoole.com
baseurl:             ''
gems: [jekyll-paginate]
paginate:            5
# paginate_path: "page:num"

# About/contact
author:
  name:              Leon 
  url:               https://twitter.com/mdo
  email:             soulhl@gmail.com

# Custom vars
# version:             1.0.0
